# =============================================================================
# BASE TEMPLATE - SPRING BOOT 4 APPLICATION CONFIGURATION
# =============================================================================
# Common Configuration - Shared across all profiles (local, prod, createdb)
# =============================================================================

spring:
  profiles:
    active: @profileName@
  application:
    name: base-template
  messages:
    basename: i18n/system-messages
    encoding: UTF-8
  # Common JPA Configuration
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: none
    defer-datasource-initialization: true
    properties:
      hibernate:
        "[default_schema]": base_template
  # Common Datasource Configuration
  datasource:
    driver-class-name: org.postgresql.Driver
    hikari:
      connection-timeout: 30000
      validation-timeout: 5000
      leak-detection-threshold: 60000
      connection-test-query: SELECT 1

# Common SpringDoc OpenAPI 3.x Configuration  
springdoc:
  api-docs:
    path: /v3/api-docs
    enabled: true
  swagger-ui:
    path: /swagger-ui.html
    enabled: true
    operations-sorter: method
    tags-sorter: alpha
    try-it-out-enabled: true
    filter: true
  show-actuator: true
  group-configs:
    - group: 'api'
      display-name: 'Base Template API'
      paths-to-match: '/api/**'

# Common Management/Actuator Configuration
management:
  endpoints:
    web:
      base-path: /actuator
  endpoint:
    health:
      show-components: always
  health:
    db:
      enabled: true
    diskspace:
      enabled: true
  info:
    env:
      enabled: true
    java:
      enabled: true
    os:
      enabled: true